# Generated by Django 4.0.5 on 2022-06-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_alter_comment_post_alter_comment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
    ]
